version: '3'

volumes:
  portainer_data:

services:
  portainer:
    image: portainer/portainer
    ports:
      - "9098:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - 'portainer_data:/data portainer/portainer'

  rabbitmq:
    image: rabbitmq:3.7.14-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

#  db:
#    image: postgres
#    restart: always
#    ports:
#      - 32771:5432
#    volumes:
#      - /home/emerio/Documents/nitip/indo-cms/postgresql-data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_PASSWORD: password

#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - 8282:8080


